// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package goproto_test

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Test struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Weight               []int32  `protobuf:"varint,3,rep,packed,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test) Reset()         { *m = Test{} }
func (m *Test) String() string { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()    {}
func (*Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test.Unmarshal(m, b)
}
func (m *Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test.Marshal(b, m, deterministic)
}
func (m *Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test.Merge(m, src)
}
func (m *Test) XXX_Size() int {
	return xxx_messageInfo_Test.Size(m)
}
func (m *Test) XXX_DiscardUnknown() {
	xxx_messageInfo_Test.DiscardUnknown(m)
}

var xxx_messageInfo_Test proto.InternalMessageInfo

func (m *Test) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Test) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Test) GetWeight() []int32 {
	if m != nil {
		return m.Weight
	}
	return nil
}

type PandaResponse struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMsg             string   `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PandaResponse) Reset()         { *m = PandaResponse{} }
func (m *PandaResponse) String() string { return proto.CompactTextString(m) }
func (*PandaResponse) ProtoMessage()    {}
func (*PandaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

func (m *PandaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PandaResponse.Unmarshal(m, b)
}
func (m *PandaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PandaResponse.Marshal(b, m, deterministic)
}
func (m *PandaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PandaResponse.Merge(m, src)
}
func (m *PandaResponse) XXX_Size() int {
	return xxx_messageInfo_PandaResponse.Size(m)
}
func (m *PandaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PandaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PandaResponse proto.InternalMessageInfo

func (m *PandaResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *PandaResponse) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*Test)(nil), "goproto_test.test")
	proto.RegisterType((*PandaResponse)(nil), "goproto_test.PandaResponse")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0x8e, 0xbf, 0x0a, 0xc2, 0x40,
	0x0c, 0x87, 0xa9, 0xfd, 0x83, 0x0d, 0x0a, 0x92, 0x41, 0x0a, 0x22, 0x94, 0x4e, 0x9d, 0x5c, 0x7c,
	0x04, 0xdd, 0x44, 0x90, 0xbc, 0x40, 0x39, 0x6d, 0x38, 0x1d, 0x7a, 0x29, 0x77, 0x07, 0xbe, 0xbe,
	0x5c, 0xea, 0x94, 0xef, 0xf7, 0x0d, 0x1f, 0x01, 0x88, 0x1c, 0xe2, 0x69, 0xf6, 0x12, 0x05, 0x37,
	0x56, 0x14, 0x86, 0xe4, 0xba, 0x2b, 0x14, 0xe9, 0x22, 0x42, 0xe1, 0xcc, 0xc4, 0x4d, 0xd6, 0x66,
	0x7d, 0x4d, 0xca, 0xb8, 0x83, 0xdc, 0x58, 0x6e, 0x56, 0x6d, 0xd6, 0x97, 0x94, 0x10, 0xf7, 0x50,
	0x7d, 0xf9, 0x63, 0xdf, 0xb1, 0xc9, 0xdb, 0xbc, 0x2f, 0xe9, 0xbf, 0xba, 0x1b, 0x6c, 0x1f, 0xc6,
	0x8d, 0x86, 0x38, 0xcc, 0xe2, 0x02, 0xe3, 0x11, 0x80, 0xbd, 0x17, 0x3f, 0xbc, 0x64, 0x5c, 0xa2,
	0x25, 0xd5, 0x6a, 0x2e, 0x32, 0x32, 0x1e, 0x60, 0x19, 0xc3, 0x14, 0xac, 0xf6, 0x6b, 0x5a, 0xab,
	0xb8, 0x07, 0xfb, 0xac, 0xf4, 0xbd, 0xf3, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x9a, 0xc5, 0x6f, 0x87,
	0xb5, 0x00, 0x00, 0x00,
}
